name: 1riel

services:

  mongodb:
    # database
    build:
      context: .
      dockerfile: services/mongodb/Dockerfile
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/data/db:/data/db
      - ./database/mongodb/data/configdb:/data/configdb
    restart: unless-stopped


  minio:
    # object storage
    build:
      context: .
      dockerfile: services/minio/Dockerfile
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./database/minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    

  # will be removed
  telegram:
    # telegram bot
    build:
      context: .
      dockerfile: services/telegram/Dockerfile
    container_name: telegram
    env_file:
      - .env
    restart: unless-stopped


  server:
    # backend server
    build:
      context: .
      dockerfile: services/server/Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    # frontend client
    build:
      context: .
      dockerfile: services/client/Dockerfile
    container_name: client
    env_file:
      - .env
    ports:
      - "80:80"
    restart: unless-stopped

